[project]
name = "demux-realm"
version = "0.0.1"
description = "Yggdrasil realm for demultiplexing planning and pre-demux metadata preparation"
authors = [
    { name = "Sara Sjunnebo", email = "sara.sjunnebo@scilifelab.se" },
    { name = "Anastasios Glaros", email = "anastasios.glaros@scilifelab.se" }
]
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "pandas",
    "click",
]

[project.optional-dependencies]
ygg = [
    "yggdrasil @ git+https://github.com/NationalGenomicsInfrastructure/Yggdrasil.git@dev",
]

dev = [
    "ruff>=0.11.8",
    "pytest",
    "pytest-asyncio>=0.21",
]

[project.entry-points."ygg.realm"]
dmx_realm = "demux_realm.descriptor:get_realm_descriptor"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["demux_realm*"]

[tool.pyright]
extraPaths = ["../Yggdrasil"]

[tool.mypy]
mypy_path = ["../Yggdrasil"]

[[tool.mypy.overrides]]
module = ["pytest"]
ignore_missing_imports = true
